# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Data Kampus
email: azrulhaifan@rocketmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web Developer - Graphic Artist - User Experience Designer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://datakampus.web.id" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: azrulhaifan
github_username:  azrulhaifan
facebook_username: azrul.njsg
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
#linkedin_url: https://

# Address information
address_street: Jalan Raya Prupuh Panceng RT 5 RW 2
address_city: Gresik
address_state: ID
address_zip: 61156

# Build settings
markdown: kramdown
